### ISSUE TITLE
Installation instruction on https://bashhub.com/docs

### ISSUE THREAD

**Issue by leni536** [rcaloras/bashhub-client#4]
Well, it's not a client bug, I post it here anyway.

The installation instruction reads:
```
curl -OL bashhub.com/setup && bash setup
```

Should be:
```
curl -OL https://bashhub.com/setup && bash setup
```

I know that the original redirects to the https one, however it doesn't prevent a MITM attacker from hijacking the first http request and response with a tampered setup file.

**Comment by rcaloras** [comment]
Hey thanks for the feedback and good eye!  I updated it on the docs and all other installation instructions. 

Would love for you to give bashhub a try if you're interested? Curious as to how you found my project :)

**Comment by leni536** [comment]
I just looked into better history handling for bash and I wanted to implemented it with using sqlite3. I needed a preexec hook so I came across your project and it seems like something I exactly want except the centralized bashhub.com storage of my history.

Right now I wrote a really simple sqlite3 history handling in bash using your preexec implementation. I  really would like to use your bashhub software but only if I can host it my own. Are you planning to share server sources?

**Comment by rcaloras** [comment]
Thanks for the feedback! I don't intend to open source/share the server at this time. Maybe somewhere down the road. I'm planning on building a public facing api for it though.

My goal has been to save every command you enter on any system and provide an easy interface to search and share it from. I believe a centralized place for that is the easiest. I want bashhub to be to terminal commands the way github is to source code. The main difference being commands should be private by default rather than public (github's model). If you're concerned about sensitive data, it's something I'm actively working on/thinking about. There's a handful of options to ignore commands and or turn off bashhub. Also data is encrypted in transfer and at rest. Would love to talk more if you have some other ideas or suggestions to convince you to give it a shot.

I have a few dozen users and I'm actively developing the project. I'd encourage you to try it on a single system first and see how it impacts your flow. Uninstall and removing it is super simple. Removing the terminal hook and then:
```bash
rm -r ~/.bashhub
```
You can find me at https://bashhub.com/u/rccola. Thanks for your time and checking it out!
