### ISSUE TITLE
Any way to upload old zsh_history or bash_history files?

### ISSUE THREAD

**Issue by jaredmichaelwilliams** [rcaloras/bashhub-client#42]
Would love to upload the already made zsh_history files that have been collecting for 30,000+ commands

**Comment by rcaloras** [comment]
Hey @jaredmichaelwilliams,

Yes, there is a way. You can save anything to bashhub’s api using bashhub save which is how commands are processed. The only problem is for these existing commands you won’t have contextual information about them (e.g. Path, Session, etc). You'll have to provide some defaults.

```bash
bashhub save --help
Usage: bashhub save [OPTIONS] COMMAND PATH PID PROCESS_START_TIME EXIT_STATUS

  Save a command to Bashhub

Options:
  -h, --help  Show this message and exit.
```

You can save whatever you want by providing defaults like:
`bashhub save "$any_command_here" /tmp 0 0 0`

You should be able to write a small script that'll process them.

**Comment by rcaloras** [comment]
Closing. @jaredmichaelwilliams feel free to reopen if you have any other questions. :+1:

**Comment by sbrl** [comment]
Doing something like this:

```bash
while read -r command; do bashhub save "${command}" / 0 0 0; echo "${command}"; done <~/.bash_history
```

....is certainly possible, but it's not very efficient because for every command it has to start a new subprocess, and if you've got a few thousand commands it's gonna take a _long_ time.

I would argue that a new subcommand is needed to import a list of commands in a text file (1 per line) to make it more efficient.
