### ISSUE TITLE
Does not find some commands

### ISSUE THREAD

**Issue by segurac** [rcaloras/bashhub-client#50]
Hi, thanks for making the client open source. 
I just installed it, but it seems to not be able to find the command "which"
Example:

$ which python
/usr/bin/python
$ bh which
$ bh  python
which python

**Comment by rcaloras** [comment]
Wow, that's super weird. This must be something with the search implementation. @segurac thanks for reporting! Let me know if there's anything else you notice. 

I'll check into it this weekend. Thanks for reporting.

**Comment by rcaloras** [comment]
Looked into this a few weeks back. This is actually due to Bashhub's search index classifying `which` as a stop word. The index should be language agnostic and I can configure it to not use any of these.

I'm planning on migrating the database and text index to a new hosting platform in the coming weeks. When I do that I'll also rebuild the text index to not be configured for any language which should omit stop words. @segurac thanks for reporting! I'll leave this open and close one it's rebuilt.

**Comment by rcaloras** [comment]
Closing this as duplicate of https://github.com/rcaloras/bashhub-client/issues/64

**Comment by rcaloras** [comment]
This has been fixed in #64
