### ISSUE TITLE
Error in MacOS Sierra

### ISSUE THREAD

**Issue by vik-y** [rcaloras/bashhub-client#62]
After using the normal installation method given on the website: After every command that I enter I am getting this error message: `__bh_precmd:19: no such file or directory: /Users/vikas.y/.bashhub/log.txt`. Also no commands are getting synced.

**Comment by vik-y** [comment]
For now I fixed it by modifying the __bh_precmd function in `deps/lib-bashub.sh`

```
if [[ -e "$bashhub_dir" ]]; then
        (__bh_process_command "$command"&) >> "$bashhub_dir"/log.txt 2>&1
# Remove "/" from above line fixes the issue for me in mac but I'm sure this would break things on linux. 
    fi;
```

**Comment by rcaloras** [comment]
@vik-y Thanks for opening! Not sure I understand exactly what the problem is. Looks like something with how output is being logged is breaking the invocation of `__bh_process_command`. https://github.com/rcaloras/bashhub-client/blob/master/bashhub/shell/deps/lib-bashhub.sh#L67 

What did you change in that code block? Can you paste your current code block? Looks like you just added a comment, I don't see what you changed.

**Comment by vik-y** [comment]
I changed this : 
```sh
        (__bh_process_command "$command"&) >> "$bashhub_dir"/log.txt 2>&1
```
to this
```sh
        (__bh_process_command "$command"&) >> "$bashhub_dir"log.txt 2>&1
```
Notice carefully, in the first code block: "/log.txt" is there but in second block "log.txt" is there so essentially I removed a "/" . After this change I created `/Users/vikas.y/.bashhub/log.txt` file manually and things started working magically, I have no idea why. :D

**Comment by rcaloras** [comment]
I understand creating the log.txt considering it didn't exist previously. (It still should be auto created by `>>` in the event it's not there). Removing the `/` doesn't make sense since bash should disregard any additional `/` added. 

One thing you could try is to uninstall and reinstall and see if you get the same errors:

```bash
rm -r ~/.bashhub
curl -OL https://bashhub.com/setup && bash setup
```
Thanks for the feedback @vik-y!

**Comment by vik-y** [comment]
Same error with re installation. Yesterday a similar error popped while I was installing it on a linux system too. I tried the above fix because I had used a tool earlier which had similar issue and removing `/` helped.

**Comment by rcaloras** [comment]
This is very confusing as I've never heard of this issue before. Do you have to create the log manually and remove `/`? My guess is the backslash is preventing the log from getting created for some reason. That could be changed to simply `touch` that file during installation. 

Could you try reinstalling and simply creating that file when it's erroring. e.g:

```
touch /Users/vikas.y/.bashhub/log.txt
```

**Comment by vik-y** [comment]
Yes, it looks like just creating the log.txt fixes the issue and there is no need of removing `/` . Looks like I tried to overfix the problem. :D 

But anyway the absence of log.txt is a problem which needs to be resolved. Thanks for the help.
