### ISSUE TITLE
support python 3.8

### ISSUE THREAD

**Issue by yeus** [rcaloras/bashhub-client#93]
installation on machine with python3.8 gives:

`
  Sorry can't seem to find a version of python 3.5-3.7 or 2.7 installed
`

**Comment by rcaloras** [comment]
@yeus thanks for the feedback. I put together a patch (https://github.com/rcaloras/bashhub-client/commit/d2e16a53deb3ece5e99a147b9c6521da4d864dac) to support this and it's working for me locally, mind testing it out? You can run:


```bash
# Pulls down setup with the latest patch
curl https://bashhub.com/setup?version=2.1.3-dev -Lo setup && bash setup
```


FWIW I originally put in support for 3.8 when migrating to python3, but removed it due to some issues with libraries at the time in https://github.com/rcaloras/bashhub-client/commit/4fbfa9ae3c7a39706a2a20b698b3a04df089925f I think these may be resolved now so we can add them back.

**Comment by rcaloras** [comment]
@yeus any luck?

**Comment by yeus** [comment]
yes looks good!  thanks for the update u r awesome!
